backend:
  name: git-gateway # https://github.com/netlify/netlify-cms
  branch: main # 要更新的分支(可选；默认为主分支)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "/themes/fluid/source/img" # 媒体文件将存储在图片/上载下的Repo中。
public_folder: "/img" # 上传的媒体的src属性将以/images/uploads开头。

site_url: https://www.brightunion.xyz # 网站网址
display_url: https://www.brightunion.xyz # 显示网址
logo_url: https://www.brightunion.xyz/img/bucms.png

locale: "zh_Hans" # 语言环境 https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-locales/src

auto_generator:
  post: 
    # 如果你有多个Post文件夹，在这里定义多个，见https://github.com/jiangtj/blog/blob/master/netlify-cms.yaml
    all_posts:
      # 设置为false，关闭默认的Post
      enabled: false
      label: "Post"
      folder: "source/_posts"
      create: true
      editor:
        preview: true
  # Page生成配置
  page: 
    enabled: false
    config:
      label: "Page"
      # 默认禁止删除Page文件
      delete: false
      editor:
        preview: true

collections:      # https://www.netlifycms.org/docs/configuration-options/#collections
  - name: "posts" # 在路由中使用，例如：/admin/collections/blog。
    label: "文章" # 在用户界面中使用
    description: "欢迎使用光明联盟·网站内容管理系统，如果遇到使用方面的问题，请先查阅“使用说明”：https://wiki.brightunion.xyz/ ，若不能解决再联系管理员。祝您使用愉快！"
    folder: "source/_posts" # 存储文件的文件夹的路径。
    create: true # 允许用户在这个集合中创建新的文件。
    fields: # 每份文件的字段，通常是前面的内容。
      - {label: "标题", name: "title", widget: "string"}
      - label: "分类"
        name: "categories"
        widget: "select"
        options: ["理论文章", "红色曙光快讯", "光联动态"]
      - {label: "作者", name: "author", widget: "string", required: false} 
      - {label: "摘要", name: "excerpt", widget: "list", required: false, hint: '网站首页的文章摘要最多显示 3 行，当屏幕宽度不足时会隐藏超出的摘要部分。'}
      - {label: "文章页顶部大图", name: "banner_img", widget: "image", required: false} 
      - {label: "文章在首页的封面图", name: "index_img", widget: "image", required: false} 
      - {label: "内容", name: "body", widget: "markdown", required: false, hint: '请尽量不要使用中文输入法编辑文章，否则可能出现光标错位/偏移问题。请尽量不要使用手机UA进行编辑，如果手机端操作请开启“访问电脑版”模式，否则可能编辑失效。如果在 Windows 端写/修改文章，建议先在记事本或者 Word/WPS 上写好，再粘贴至网站内容管理系统的编辑框，以免编辑失效。' }
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      # - {label: "更新日期", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      - {label: "永久链接", name: "permalink", widget: "string", required: false, hint: '填写的字符串请以“/”结尾。示例：若你希望将文章网址设置为“https://www.brightunion.xyz/example/ ”，则填入“example/”。'}
      - {label: "标签", name: "tags", widget: "list", required: false, hint: '多个标签之间请使用英文标点“, ”进行区分。'}
      #- {label: "分类", name: "categories", widget: "list", required: false}

      - {label: "文章排序权重", name: "sticky", widget: "number", required: false, hint: '输入数值，数值越大，该文章越靠前，达到类似于置顶的效果。若此行留空，文章将按默认排序。'}
      - {label: "隐藏文章", name: "hide", widget: "boolean", default: false, required: false, hint: '打开此开关后，网站首页、分类页和标签页将不会显示此文章，但依然可以通过文章链接访问此文章。'}
      - {label: "文章加密密码", name: "password", widget: "string", required: false, hint: '在此输入设定的密码以加密文章，设定密码后访客浏览时需要输入设定的密码才能查看文章。若不输入，则文章不会被加密'}
      #  comment: 'This is a multiline\ncomment'
      # - {label: "评论区", name: "comments", widget: "boolean", default: true, required: false}
      # - {label: "关键词", name: "keywords", widget: "list", required: false}
    editor:
      preview: true
